version: '3'

services:
  web:
    build: .
    command: "uvicorn TParser.fast:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017